### ISSUE TITLE
blivet umountFilesystems transforms lvm thinpools into normal volumes

### ISSUE THREAD

**Issue by soul9** [storaged-project/blivet#645]
When using livemedia-creator my lvm thinpool is converted to a normal lv on umountFilesystems step.
Example (using centos-7.ks from https://github.com/CentOS/sig-cloud-instance-build/tree/master/docker )
```
$ sudo lvcreate -L 19.9G -n docker -T myvg
$ sudo lvs
  LV     VG                Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker myvg twi-a-tz--  19.90g             0.06   0.57                            
$ sudo livemedia-creator --no-virt --make-tar --ks centos-7.ks --image-name=centos-7-docker.tar.xz --project "CentOS 7 Docker"  --releasever "7"
2017-11-27 15:56:22,935: disk_size = 3GB
2017-11-27 15:56:22,936: disk_img = /var/tmp/centos-7-docker.tar.xz
Starting installer, one moment...
anaconda argparse: terminal size detection failed, using default width
[Errno 25] Inappropriate ioctl for device
anaconda 21.48.22.121-1 for CentOS 7 Docker 7 (pre-release) started.
15:56:24 Not asking for VNC because we don't have Xvnc
Starting automated install...........
Checking software selection
...
Generating initramfs
.
Running post-installation scripts
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/sbin/anaconda", line 75, in exitHandler
    anaconda.storage.umountFilesystems(swapoff=False)
  File "/usr/lib/python2.7/site-packages/blivet/__init__.py", line 1634, in umountFilesystems
    self.fsset.umountFilesystems(swapoff=swapoff)
  File "/usr/lib/python2.7/site-packages/blivet/__init__.py", line 2690, in umountFilesystems
    device.format.teardown()
  File "/usr/lib/python2.7/site-packages/blivet/formats/fs.py", line 924, in teardown
    return self.unmount()
  File "/usr/lib/python2.7/site-packages/blivet/formats/fs.py", line 704, in unmount
    raise FSError("umount failed")
FSError: umount failed
Error in sys.exitfunc:
.
2017-11-27 15:59:34,357: Disk Image install successful
2017-11-27 15:59:34,357: SUMMARY
2017-11-27 15:59:34,357: -------
2017-11-27 15:59:34,357: Logs are in /tmp
2017-11-27 15:59:34,357: Disk image is at /var/tmp/centos-7-docker.tar.xz
2017-11-27 15:59:34,357: Results are in /var/tmp

$ sudo lvs
  LV     VG                Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker myvg twi---tz--  19.90g

**Comment by soul9** [comment]
this might be because the mount looks broken:
```
$ mount |grep docker
/dev/mapper/myvg-root on /var/lib/docker/plugins type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/myvg-root on /var/lib/docker/devicemapper type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
```
Mind you just the entry in /proc/mounts is broken, the /dev/mapper/myvg-docker device is the one that is mounted.

**Comment by dwlehman** [comment]
Notice the 't' in the volume attributes (`twi---tz--`). That means it's a thin volume. It's not possible for any code that runs in `umountFilesystems` to convert a thin volume into a non-thin volume.

I don't think `myvg-root` has anything to do with the installation you ran. I also don't see how `myvg-docker` is related to the `livemedia-creator` run.

**Comment by soul9** [comment]
I think you are right and this was unrelated to my issue. sorry for the noise.
